/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.confluent.ps.tools;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        GetKafkaData classUnderTest = new GetKafkaData();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
