/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.confluent.ps.tools;

public class GetKafkaData {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new GetKafkaData().getGreeting());
    }
}
